/**
 * Downloads the latin subset of the three brand faces as woff2 and writes
 * a local @font-face stylesheet. Run once; the files are committed.
 *
 * Fonts are self-hosted so the site makes zero third-party requests and the
 * display face can be preloaded without a cross-origin round trip.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = resolve(here, '../public/fonts');
const CSS_OUT = resolve(here, '../src/styles/fonts.css');

// A modern Chrome UA makes the API serve variable woff2 rather than legacy ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/**
 * Two faces carry the brand, a third carries the numbers.
 *
 * Bricolage Grotesque is the display face: a variable grotesque with an
 * optical-size AND a width axis, which is what lets the headline set tight and
 * wide while a card title stays narrow — one family doing the work of three.
 * Hanken Grotesk is the body face; it is quieter than Inter at small sizes and
 * does not fight the display face for attention.
 *
 * Neither has a true italic, which is deliberate — emphasis on this site is
 * carried by the accent colour and the width axis, not by a slant.
 *
 * @type {{name:string, file:string, query:string, style:'normal'|'italic', weight:string}[]}
 */
const FACES = [
  {
    name: 'Bricolage Grotesque',
    file: 'bricolage-grotesque-latin-var.woff2',
    query: 'Bricolage+Grotesque:opsz,wdth,wght@12..96,75..100,300..800',
    style: 'normal',
    weight: '300 800',
  },
  {
    name: 'Hanken Grotesk',
    file: 'hanken-grotesk-latin-var.woff2',
    query: 'Hanken+Grotesk:wght@300..700',
    style: 'normal',
    weight: '300 700',
  },
  {
    name: 'JetBrains Mono',
    file: 'jetbrains-mono-latin-var.woff2',
    query: 'JetBrains+Mono:wght@400..600',
    style: 'normal',
    weight: '400 600',
  },
];

/** Pull the `latin` unicode-range block out of a Google Fonts css2 response. */
function extractLatin(css) {
  const blocks = css.split('@font-face').slice(1);
  // The latin block is the one whose unicode-range starts at U+0000.
  const latin =
    blocks.find((b) => /unicode-range:[^;]*U\+0000-00FF/i.test(b)) ??
    blocks[blocks.length - 1];
  // Only Google's own font host, and only a range that is actually a range —
  // both values end up in committed files (the binary, the generated CSS).
  const url = latin.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/i)?.[1];
  const range = latin.match(/unicode-range:\s*([^;]+);/i)?.[1]?.trim();
  if (!url) throw new Error('no fonts.gstatic.com woff2 url found in css block');
  if (range && !/^U\+[0-9A-Fa-f?-]+(,\s*U\+[0-9A-Fa-f?-]+)*$/i.test(range)) {
    throw new Error(`unexpected unicode-range: ${range}`);
  }
  return { url, range };
}

await mkdir(FONT_DIR, { recursive: true });

const faceRules = [];

for (const face of FACES) {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${face.query}&display=swap`;
  const css = await fetch(cssUrl, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`${face.name}: css fetch ${r.status}`);
    return r.text();
  });

  const { url, range } = extractLatin(css);
  const bin = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`${face.name}: font fetch ${r.status}`);
    return r.arrayBuffer();
  }));

  await writeFile(resolve(FONT_DIR, face.file), bin);
  console.log(`${face.name} ${face.style} -> ${face.file}  ${(bin.length / 1024).toFixed(1)} KB`);

  faceRules.push(
    [
      '@font-face {',
      `  font-family: '${face.name}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${face.file}') format('woff2');`,
      range ? `  unicode-range: ${range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n')
  );
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n`;
await mkdir(dirname(CSS_OUT), { recursive: true });
await writeFile(CSS_OUT, header + faceRules.join('\n\n') + '\n');
console.log(`\nwrote ${CSS_OUT}`);
